### ISSUE TITLE
Add commands to show installed candidates and ones with available updates

### ISSUE THREAD

**Issue by mpassell** [gvmtool/gvm-cli#269]
I'm thinking of commands analogous to *brew list* (shows which formulae you've installed) and *brew outdated* (out of the the formulae you have installed, which have uninstalled updates).

**Comment by nobeans** [comment]
Absolutely agreed.
So, I've implemented it as gvm-extensions: https://github.com/nobeans/gvm-extensions/blob/feature/outdated/src/main/resources/extensions/gvm-outdated.sh

Installation:
```
$ curl https://raw.githubusercontent.com/nobeans/gvm-extensions/feature/outdated/src/main/resources/extensions/gvm-outdated.sh > ~/.gvm/ext/gvm-outdated.sh
```

Usage:
```
$ gvm outdated
griffon (0.9, 1.2.0 < 1.5.0)
vertx (2.0.1-final, 2.0.2-final, 2.0.2.final < 2.1.5)
```

It works for me on Mac OS X!

**Comment by mpassell** [comment]
Thanks! Works for me, too. Pull request?

**Comment by nobeans** [comment]
What do you think about sending the PR of my extension to gvm-cli? > @marcoVermeulen

**Comment by marcoVermeulen** [comment]
Sorry, I wasn't watching this thread. I love it!

If you would be willing we could even make it part of the CLI itself. That would mean the usual acceptance tests etc. If not, I can simply merge your PR.

**Comment by nobeans** [comment]
I'm slowly trying to wrap up my work for `outdated` at this branch...
https://github.com/nobeans/gvm-cli/tree/gvm-outdated

**Comment by marcoVermeulen** [comment]
Nice! Do you have some cukes for me to look at?

**Comment by marcoVermeulen** [comment]
Don't worry, found it ;-)

**Comment by nobeans** [comment]
There is a cuke test but all the things are still under way.

TODO:

* Prepare a test env
    * In my environment, existed tests are failing somehow...
* Complete the outdated test
    * It needs to add some steps for the "Given" conditions.
* Fix the known bug

BTW, should I make a new WIP pull request?

**Comment by marcoVermeulen** [comment]
Let's wait until you are feature complete, then we can do a PR straight to
master.

**Comment by marcoVermeulen** [comment]
Just managed to have a read through the cucumber and it looks great! Looking forward to having this in the CLI!

**Comment by nobeans** [comment]
Glad to hear that. But some tests haven't passed yet. I'll fix them and then send a new PR to gvm-cli.

**Comment by marcoVermeulen** [comment]
Cool, also if you can try squashing your commits into a single one with
appropriate commit message once you're done.

**Comment by nobeans** [comment]
Finally, tests passed! I've just sent a PR: https://github.com/gvmtool/gvm-cli/pull/318

**Comment by marcoVermeulen** [comment]
The PR #318 has been merged, but I've left some comments for further enhancement.

**Comment by mpassell** [comment]
`gvm outdated` works great for me so far. Thanks! Should I just create a separate issue for the equivalent of `brew list` so that this one can be closed?

**Comment by marcoVermeulen** [comment]
Sure, and simply describe the kind of behaviour you would like to see. I'm
a Linux user, so not too familiar with how brew works :-P

**Comment by nobeans** [comment]
If you want a command like `brew list`, you should run `gvm current` before creating new issue.

**Comment by mpassell** [comment]
Oh, I wasn't aware of that command. Thanks @nobeans! That's actually better than the output of `brew list`. Do you think it would be hard to modify `current` to show the installed versions and the one set to current for each installed candidate? I'm thinking of a display similar to what you show for `outdated`.

**Comment by marcoVermeulen** [comment]
It sounds like what you're looking for is the list command. This does what
you are looking for on a per candidate basis.

I'd prefer to keep current simple, showing only the current versions as the
name suggests.

**Comment by mpassell** [comment]
Yeah, I knew about `list`. Fair enough about keeping `current` simple. I'm very happy with `outdated`, so I'll close this.
