### ISSUE TITLE
Allow insecure certificates for downloads

### ISSUE THREAD

**Issue by bwijsmuller** [gvmtool/gvm-cli#278]
If for some reason the certicate chain is invalid (self signed for example) the gvm tool fails because of curl not downloading.
I fixed this problem in my case by adding " --insecure --ssl-allow-beast" to the curl download command in gvm-install.sh

It would be nice to have a setting somehow, maybe a command line option or environment variable to be able to do this without changing the source code.

**Comment by neeraj9** [comment]
I found that $HOME/.gvm/etc/config can be modified to run insecure curl. You can set "gvm_insecure_ssl=true" and the script $HOME/.gvm/src/gvm-install.sh will do the rest.

**Comment by marcoVermeulen** [comment]
This is an old task that can be closed. It was addressed with the `gvm_insecure_ssl` flag in config.
