### ISSUE TITLE
Fix initialisation of GVM when using multiple shells

### ISSUE THREAD

**Issue by ilmoralito** [gvmtool/gvm-cli#317]
Hi, and thanks for your time

just few days ago when i try gvm current grails i got

gvm current grails
Using grails version /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/chichibek/.rvm/bin:/home/chichibek/.rvm/bin

if i try 

gvm use grails 2.2.3

i get no error message

but if i try grails from command line 

i get

grails:command not found

I tyred removing and reinstalling   gvm but i get the no different result

Thanks again

**Comment by georgecodes** [comment]
Most likely when you installed GVM, it udated your PATH variable in a file that doesn't get run on login. Example: your .bash_profile file contains the gvm paths, but that isn't run for a login shell. Check the following files

~/.bashrc
~/.bash_profile
~/.profile

and see which one - if any - contains a PATH variable that refers to .gvm.

**Comment by mskomrak** [comment]
I'm having the same issue. Using zsh 5.0.5 with oh-my-zsh and Ubuntu 14.10 x64.

After a successful gvm install groovy 2.4.3, gvm list groovy reports 2.4.3 as installed (but not in use). However gvm current groovy prints out:
`
Using groovy version <my path data>
`
Running the use and default commands does not help, although they run successfully, so I still get
`
zsh: command not found: groovy
`

There's a gvm-init.sh in my .gvm/bin, and a 2.4.3 folder in .gvm/groovy.  
My .zshrc, .profile and .bashrc all include [[ -s "/home/mislav/.gvm/bin/gvm-init.sh" ]] && source "/home/mislav/.gvm/bin/gvm-init.sh".

**Comment by dmunguia** [comment]
Hi, I'm having the same issue. 

I'm using:
+ ubuntu 14.10 x64.
+ zsh 5.0.5 (x86_64-pc-linux-gnu) 
+ oh-my-zsh 
+ GVM version 2.4.1
+ groovy 2.4.3 (installed through gvm)
+ gradle 2.3 (installed through gvm)

If I invoke groovy or gradle directly from their install folders they work fine: `~/.gvm/groovy/current/bin/groovy`. 

If invoke them as if they were on the PATH I get `zsh: command not found: groovy`.

`gvm current groovy` prints out my PATH info:
`Using groovy version /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

The reference to `gvm-init.sh` is in `.zshrc`, `.bashrc` and `.profile`:
`#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
[[ -s "/home/diegomunguia/.gvm/bin/gvm-init.sh" ]] && source "/home/diegomunguia/.gvm/bin/gvm-init.sh"`

After sourcing `gvm-init.sh` there's still no reference to gvm in the PATH:

```
➜  source "/home/diegomunguia/.gvm/bin/gvm-init.sh"
➜  echo $PATH                                      
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by steveash** [comment]
I had this same problem, however, upon restart it was back to normal.  Looking at the script I see that it sets this GVM_INIT flag to true the first time it runs.  Thus running source gvm-init.sh multiple times wont re-export the PATH multiple times.  So I concluded that obviously something else overwrote my PATH (ive got docker and a whole bunch of other stuff going on- not sure about the culprit) and then I wasted an hour trying to figure out why gvm wasn't working :/  In any case maybe the suggested improvement would be to move that JVM_INIT check lower in the script, after the PATH export so even in the worst case re-sourcing the gvm-init would correct any PATH problems.

**Comment by moaxcp** [comment]
Is there a workaround for this or a way to downgrade gvm?

**Comment by marcoVermeulen** [comment]
I've managed to replicate it and am working on a fix at the moment.

@hho Moved the discussion here from #253. It seems like it happens when `gvm-init.sh` has already been sourced, and subsequent shells try to source it again. I'm playing around with changing the what happens _before_ we escape the init script on subsequent sourcing if `GVM_INIT` is true.

#306 is a pull request that was not accepted because it made radical changes to fundamental behaviour of gvm which I did not approve of.

**Comment by ilmoralito** [comment]
Does exist a solution for this problem?

**Comment by marcoVermeulen** [comment]
Yes, it has been fixed. Are you still experiencing this?

**Comment by ahoffmann-wi** [comment]
I am experiencing this issue. I installed GVM on a fresh system yesterday (July 25) purportedly after it was fixed. I installed Grails version 3.0.3 using GVM.  I am running zsh version 5.0.7 with oh-my-zsh. After restarting the shell or even when manually sourcing `~/.gvm/bin/gvm-init.sh`, I get the following error when running the `grails` command:

```
zsh: command not found: grails
```

The path is not being set correctly. When running `gvm current grails` I get:

```
Using grails version /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

I can confirm that is also my PATH.

**Comment by ilmoralito** [comment]
I am experimenting the same problem, i have Groovy enVironment Manager 2.4.2, when i try to update 

gvm selfupdate
No update available at this time.

++++++++++++++++++++

➜  ~  gvm current grails
Using grails version /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/chichibek/.rvm/bin

**Comment by marcoVermeulen** [comment]
@ilmoralito can you try commenting out RVM in your `. zshrc` and let me know if that solves the problem? I've experienced similar issues with RVM, zsh and ohmyzsh in the past.

**Comment by ilmoralito** [comment]
@marcoVermeulen thanks for answer

I just commented out RVM in .zshrc and no solved the problem

**Comment by ilmoralito** [comment]
I fully remove gvm following instructions listed in http://forum.gvmtool.net/Uninstall-gvmtools-td44.htm.

Then i tried to install gvm again and installed grails in this case verion 2.2.3, after this steps i am still getting this error message after i try grails current version

Using grails version /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

If i try grails, i get:

zsh: command not found: grails

I will appreciate a help.

**Comment by marcoVermeulen** [comment]
It is very difficult to diagnose issues when not knowing what platform you are on. Are you on Linux/OSX? Are you using ohmyzsh? ZSH version?

**Comment by ilmoralito** [comment]
You are right.

I am using ubuntu 14.04, and zsh

2015-08-24 10:10 GMT-06:00 Marco Vermeulen <notifications@github.com>:

**Comment by marcoVermeulen** [comment]
Try commenting out any exports of PATH in your `.zshrc`. I had this and it resolved the issue for me.

In my case, it was due to dodgy configuration of `/usr/local/*` related paths exported to `PATH` when ohmyzsh created the `.zshrc` file. At the point when zsh parses the file, it stops any further exports of `PATH` due to invalid entries.

**Comment by ilmoralito** [comment]
Thanks @marcoVermeulen  its working now, i commented out

# export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

in User configuration section

Thanks for your time

**Comment by marcoVermeulen** [comment]
It's a great pleasure!

**Comment by byteshiva** [comment]
Why mess with gvm settings, i have installed gvm and sdk. Now sdk is setting alias as gvm

**Comment by marc0der** [comment]
If you take a look on the [Usage Page](http://sdkman.io/usage.html#config) of our website, you will see that we provide a config to switch this off.

You will see a section like this in our docs:

    # disable GVM alias, for users of the Go Version Manager
    sdkman_disable_gvm_alias=true|false

The reason why we provide this config is because some people still like to call sdkman _gvm_ (which it was previously called before we decided to change the name).

**Comment by byteshiva** [comment]
@marc0der - Thanks for pointing me in the right direction. it worked. Now I can keep both golang version manager and sdkman together. Thanks Again

**Comment by Dibyojyoti** [comment]
Hello, I am using the Docker image ubuntu:latest provided as official image in docker hub. I try to make a new image by installing java and groovy using sdk, through a dockerfile. but it says /bin/sh: sdk: command not found. but if I install it in side a docker container manually it runs fine. is there any catch? I examined ~/.bashrc and ~/.profile both has [[ -s "/root/.sdkman/bin/sdkman-init.sh" ]] && source "/root/.sdkman/bin/sdkman-init.sh" at last line.
