### ISSUE TITLE
Conflicts with Grails embedded groovy and a stand alone version of groovy

### ISSUE THREAD

**Issue by ejaz-ahmed** [gvmtool/gvm-cli#322]
I have been using Groovy (unpacked version) and Grails (installed thru gvm).Today I switched to gvm version of grails and it has conflicts with groovy which comes with grails. Actually grails.converters package was not visible to my application and it was complaining about JSON and XML classes. I had to remove groovy to fix this.

**Comment by marcoVermeulen** [comment]
Your problem seems very odd because the Grails SDK comes with it's own groovy binaries embedded. GVM does not manage dependencies.

**Comment by marcoVermeulen** [comment]
Any news on this or can we close this issue?

**Comment by ejaz-ahmed** [comment]
Hi marco,
I haven't made any progress in fixing this issue. We'll have to teach gvm how to manage dependencies which in my opinion is hard route to follow right now. It is better to document this limitation. I have reverted back to non-gvm version of Groovy for my Groovy only projects and gvm for grails/gradle tasks.

**Comment by marcoVermeulen** [comment]
There is no plan to ever make gvm dependency aware. As I said, the problem
must be your local setup as nobody else has reported this issue.

**Comment by ejaz-ahmed** [comment]
Marco, you are right. I can't reproduce this on my VM. Probably some issue with my dev machine environment. I am closing this as it can't be reproduced.
