### ISSUE TITLE
All Codehaus services are terminated => Can't install old version of groovy

### ISSUE THREAD

**Issue by geektortoise** [gvmtool/gvm-cli#331]
Hello ! 
I have a problem when I try to install any version of groovy previous to 2.2.2

```
root@756e31c61711:/tmp# gvm install groovy 2.2.1

Downloading: groovy 2.2.1

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   319    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /root/.gvm/archives/groovy-2.2.1.zip or
        /root/.gvm/archives/groovy-2.2.1.zip.zip, and cannot find /root/.gvm/archives/groovy-2.2.1.zip.ZIP, period.

Stop! The archive was corrupt and has been removed! Please try installing again.
```

I made some tests and It seems that the url is 
```
http://api.gvmtool.net/download/groovy/2.2.1?platform=Linux
```
and in my browser, when I try to reach this URL, I have the following error message
```
All Codehaus services will be terminated progressively until May 17th 2015
```

Do you have another URL for the different groovy versions (I need the 1.8.6 :D) ?

Thanks.

**Comment by marcoVermeulen** [comment]
That is not the final URL, it's merely directing to codehaus to get the original binaries. With codehaus EOL, we have lost all the binaries of older versions.

The groovy team are currently aware of this and trying to locate the binaries. Once they are hosted again I will add them back to GVM.

**Comment by psramkumar** [comment]
groovy 221 not present in the list 

```
gvm install groovy 2.2.1
```

**Comment by marcoVermeulen** [comment]
Erm, yes. Please read my previous message above.

**Comment by marcoVermeulen** [comment]
@glaforge do we have any news on the restoration of the old binaries yet?

**Comment by glaforge** [comment]
Our friends from JFrog are actually working on it, and we should hopefully have the old binaries on Bintray soon (before the end of the week hopefully)

**Comment by marcoVermeulen** [comment]
Excellent news. Thank you!

**Comment by glaforge** [comment]
All the old releases should now be on Bintray like the newer ones!

**Comment by glaforge** [comment]
All the old releases should now be on Bintray like the newer ones!

**Comment by glaforge** [comment]
All the old releases should now be on Bintray like the newer ones!

**Comment by glaforge** [comment]
You can view them here:
https://bintray.com/groovy/maven/groovy/view
(but I have the impression the 1.0.x are missing, but we didn't have them in GVM anyway, if I recall correctly)

**Comment by marcoVermeulen** [comment]
That's fantastic news, thanks!

**Comment by marcoVermeulen** [comment]
BTW, we did have all the  1.0.x versions but don't think anyone was really using them.

**Comment by glaforge** [comment]
Ah okay, I thought we had only 1.5 onward.
We'll see if JFrog manages to add them too, at least for historical purpose :-)

**Comment by r04r** [comment]
@marcoVermeulen Has this issue been resolved? I just updated gvm to version 2.4.2 and am not able to `gvm install grails 1.3.4`

**Comment by marcoVermeulen** [comment]
@r04r only the versions available on BinTray will be served from gvm.
Please refer to https://bintray.com/groovy/maven/groovy/view.

**Comment by r04r** [comment]
@marcoVermeulen Sadly it seems 1.3.4 is not available there. It is however available under https://grails.org/download.html which serves it from https://github.com/grails/grails-core/releases/ (https://github.com/grails/grails-core/releases/download/v1.3.4/grails-1.3.4.zip to be specific). Would it be possible to incorporate this in gvm?

**Comment by marcoVermeulen** [comment]
Only if bintray decide to host it. You will need to raise a ticket with
them if you need pre 1.5.0 versions.

**Comment by flofreud** [comment]
@marcoVermeulen He's talking about Grails.

Marco Vermeulen <notifications@github.com> schrieb am Di., 23. Juni 2015
19:57:

> Only if bintray decide to host it. You will need to raise a ticket with
> them if you need pre 1.5.0 versions.
>

**Comment by r04r** [comment]
It seems gvm downloads from http://api.gvmtool.net/download/grails/1.3.4?platform=Linux which currently redirects to http://dist.codehaus.org/grails/grails-1.3.4.zip which is dead. Can't the redirect be changed to https://github.com/grails/grails-core/releases/download/v1.3.4/grails-1.3.4.zip?

**Comment by marcoVermeulen** [comment]
Sorry, I'm confused now. This discussion is not about Grails but Groovy.
It's about Codehaus EOL and all the Groovy binaries getting lost.

**Comment by marcoVermeulen** [comment]
About Grails 1.3.4, it most certainly does seem to be there:
http://api.gvmtool.net/candidates/grails/1.3.4

**Comment by flofreud** [comment]
All Grails versions before 1.3.5 are pointing to Codehaus, too. Graeme put them all into the repository releases on Github. Therefore you could change the locations for 1.2.0 - 1.3.4 to the new offical release location: 

https://github.com/grails/grails-core/releases/download/v1.3.4/grails-1.3.4.zip

All of these eleven versions seems to be there.

**Comment by marcoVermeulen** [comment]
The database has been updated and all versions of Grails should be fully
operational again.

**Comment by r04r** [comment]
@marcoVermeulen Awesome, thank you! The download seems to be working.

Apologies for the confusion as well, I should have probably created a new ticket regarding grails & codehaus, but I just tacked it on to the existing ticket dealing with codehaus.

**Comment by marcoVermeulen** [comment]
No worries, let me know if you find any other anomalies.
