### ISSUE TITLE
Groovy 1.8.9 no longer available

### ISSUE THREAD

**Issue by samrocketman** [gvmtool/gvm-cli#332]
I realize groovy no longer releases updates for it but I think you should at least include the latest version of every major version of groovy released.

To reproduce attempt the following: `gvm install groovy 1.8.9`

**Comment by marcoVermeulen** [comment]
Please refer to #331 for the reason.

**Comment by samrocketman** [comment]
Why close the issues?  Seems like you just closed it and call it a day.  Guess I'll build it from source.

**Comment by samrocketman** [comment]
I've got a system that still has 1.8.9.
