### ISSUE TITLE
GVM Installer - corrupt res-2.4.1.zip file

### ISSUE THREAD

**Issue by emeraldjava** [gvmtool/gvm-cli#333]
I'm trying to install GVM on an ubuntu machine. I get the following error which seems related to a corrupt res-2.4.1.zip file which seems to be corrupt.

Looking for a previous installation of GVM...
Looking for unzip...
Looking for curl...
Looking for sed...
Installing gvm scripts...
Create distribution directories...
Create candidate directories...
Prime the config file...
Download script archive...
Extract script archive...
[/home/pauloconnell/.gvm/tmp/res-2.4.1.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/pauloconnell/.gvm/tmp/res-2.4.1.zip or
        /home/pauloconnell/.gvm/tmp/res-2.4.1.zip.zip, and cannot find /home/pauloconnell/.gvm/tmp/res-2.4.1.zip.ZIP, period.
Install scripts...
mv: cannot stat ‘/home/pauloconnell/.gvm/tmp/stage/gvm-init.sh’: No such file or directory
mv: cannot stat ‘/home/pauloconnell/.gvm/tmp/stage/gvm-*’: No such file or directory
Attempt update of bash profiles...
Attempt update of zsh profiles...

All done!

Please open a new terminal, or run the following in the existing one:

    source "/home/pauloconnell/.gvm/bin/gvm-init.sh"

Then issue the following command:

    gvm help

Enjoy!!!

**Comment by marcoVermeulen** [comment]
Can't seem to replicate this. Was it down to network issues on your side?

**Comment by abcfy2** [comment]
I face the similar issue. This might be the network issue. Downloading broken and can't unzip the archives. So my PR #306 contains this scene. If unzip or curl failed, exit. Do not remove the available GVM first unless successful unzip.

**Comment by marcoVermeulen** [comment]
@abcfy2 this is downloading the zip containing the scripts to be sourced on installation, so is not related to #306.

**Comment by emeraldjava** [comment]
As an example, i can access 

http://api.gvmtool.net/candidates

via a browser, but when i use the curl (v7.35) i get this

pauloconnell@pauloconnell-HP-ZBook-15:~/Tools/gvm-cli-2.4.2$ curl -GET -v http://api.gvmtool.net/candidates
* Hostname was NOT found in DNS cache
*   Trying 54.204.5.212...
* Connected to api.gvmtool.net (54.204.5.212) port 80 (#0)
> GET /candidates HTTP/1.1
> User-Agent: curl/7.35.0
> Host: api.gvmtool.net
> Accept: */*
> 
< HTTP/1.1 307 Temporary Redirect
< Location: http://xx.xx.xxx.xx/UserCheck/PortalMain?IID=5371B49B-F3D9-D1B4-20C1-D3F5B990BE0B&origUrl=aHR0cDovL2FwaS5ndm10b29sLm5ldC9jYW5kaWRhdGVz
< Connection: close
< 

Any idea how i can avoid this temporary redirect?

**Comment by emeraldjava** [comment]
I found that adding '-L' to the curl command line i can access the same url via the command line.

http://stackoverflow.com/questions/18474690/is-there-a-way-to-follow-redirects-with-command-line-curl

**Comment by emeraldjava** [comment]
I manually downloaded the content from this url

    http://api.gvmtool.net/res?platform=2.4.2&purpose=install

and saved it to a zip file. I then moved the gvm-init.sh to the bin folder and other scripts to src folder. The 

    pauloconnell@pauloconnell-HP-ZBook-15:~/Tools$ gvm offline disable
    Online mode re-enabled!
    pauloconnell@pauloconnell-HP-ZBook-15:~/Tools$ gvm install groovy
    ==== BROADCAST =============================================
    OFFLINE MODE ENABLED! Some functionality is now disabled.
    ============================================================
    Stop! groovy is not a valid candidate.

I appreciate the way I installed it ins't kosher but any suggestions on the offline mode. Yes - i did try the 'gvm offline enable' but same issue

**Comment by marcoVermeulen** [comment]
@emeraldjava the clue probably lies in the redirect location in your curl response. Seems like you're being intercepted and redirected by a proxy.

**Comment by marcoVermeulen** [comment]
Closing this issue after no reply received.
