### ISSUE TITLE
How to support fish-shell？

### ISSUE THREAD

**Issue by henry-zhuang** [gvmtool/gvm-cli#334]

**Comment by marcoVermeulen** [comment]
This was already raised in #294. We still have no plans to support fish-shell.

**Comment by marc0der** [comment]
We always welcome contributions, but at the end of the day someone needs to do the work. I (not being a fish shell user) simply don't have time to implement this support.

**Comment by betrcode** [comment]
@marc0der Totally understand! I ended up fixing it manually, but not ready to make a contribution. 

I will try to poke a friend. @ollehallin: Don't you use sdkman? (I know you are a fish man (fisherman?)) 
sdkman needs a bit of fish script to support fish users. I don't think it's a matter of porting everything to fish, perhaps just the `~/sdkman/bin/sdkman-init.sh` script. Maybe there is some auto-converter that can be used?

**Comment by marc0der** [comment]
@betrcode It would be great if we could get a solution that works for all fish shell users, I'm aware that fish has sizeable community and we would love to support them too.
