### ISSUE TITLE
Add JBoss Forge 2.17.0.Final

### ISSUE THREAD

**Issue by gastaldi** [gvmtool/gvm-cli#339]

**Comment by marcoVermeulen** [comment]
We could consider bringing JBoss Forge onboard in the future, but this would require the JBoss team to be involved so they can publish their own versions.

**Comment by gastaldi** [comment]
I am the core developer for JBoss Forge, so I guess that is fine. What is needed to do so?

**Comment by marcoVermeulen** [comment]
Excellent news! You would be required to push your own releases via GVM's
Vendor API or Gradle plugin as per this blog post
<http://www.wiredforcode.com/blog/2015/03/26/the-gvm-vendor-api>.

This typically entails a:

   - release call for minor *releases*.
   - An additional *default* call to make major releases the new default
   version.
   - A *broadcast* call to announce new releases via social media channels.


Once you are ready, please contact me directly so I can provide you with an
auth key/token pair.
