### ISSUE TITLE
Vertx executable not added to PATH

### ISSUE THREAD

**Issue by programmist** [gvmtool/gvm-cli#345]
This is a regression of the closed issue #209. 

After downloading and installing vertx, the `gvm use vertx 3.0.0` command reports, `Using vertx version 3.0.0 in this shell`, but running `vertx` results in `-bash: vertx: command not found`.  The `gvm current` command reports
```
Using:
gradle: 2.5
groovy: 2.4.4
```
I checked my `PATH` variable and `.gvm/vertx/current/bin` is *not* present (even after opening a new terminal).

Using bash on OSX 10.10.4

**Comment by programmist** [comment]
For anyone looking for a temorary work-around, add this to your .bashrc
```
PATH=$PATH:$HOME/.gvm/vertx/current/bin
```

**Comment by marcoVermeulen** [comment]
I'll be rolling out a fix for this later today. If you are adding this manually as @programmist suggests, don't forget to remove it after the upgrade.

**Comment by programmist** [comment]
Thanks for the update.

I just ran `gvm selfupdate`, removed the entry from my .bashrc file, and opened a new terminal window.  The `vertx` command is working now.

One note is that `gvm current` still doesn't report vertx as being installed.  Not a big issue for me, but thought you'd want to know.

**Comment by marcoVermeulen** [comment]
Thanks Tony, I'll take a look into that one.
