### ISSUE TITLE
Where is Griffon 2.x?

### ISSUE THREAD

**Issue by jasenj1** [gvmtool/gvm-cli#346]
My version of GVM tells me 1.5 is the latest available version of Griffon. But Griffon is at 2.3. And the Griffon web page says to use gvm to install it - it is the only way listed to install Griffon. Wha't up with that?

**Comment by russel** [comment]
Griffon no longer needs to be installed per se, it is just a downloaded dependency that you download in a Gradle (or Maven?) project. Set up a Griffon project using LazyBones or manually.

If you saw a webpage say anything about installing Griffon, it is wrong and needs updating.

**Comment by marcoVermeulen** [comment]
Yes, Griffon is no longer an SDK that is installed on your machine.

**Comment by jasenj1** [comment]
Thank you for the quick response. I guess that's the joy of software that makes big changes and has various tutorials and documentation floating around for the old versions.
