### ISSUE TITLE
Support for older Groovy versions

### ISSUE THREAD

**Issue by mcandre** [gvmtool/gvm-cli#349]
Could gvm get formulas for installing Groovy v1.7.0 and below?

**Comment by marcoVermeulen** [comment]
The older versions are available but have dropped off the list. Simply type:

    gvm install groovy 1.7.0

We have 1.5.0 -> 1.5.8, 1.6.0 -> 1.6.9, 1.7.0 -> current.

Older than 1.5.0 is no longer available as these versions were lost when we migrated from codehaus.

For this reason I'll close the issue.

**Comment by mcandre** [comment]
Thanks for the info!

Could we update the list to include 1.5.0 - 1.7.0?

**Comment by marcoVermeulen** [comment]
Don't really want the list to be bigger. Besides, nobody really uses them and they are only there for historic purposes.

**Comment by MontiMcMannus** [comment]
Hm, looking for good tool to manage java version for our projects. 
Last answer convinced me that skdman is the wrong tool to be included into the deployment chain.
