### ISSUE TITLE
PPA not available for ubuntu 14.04 and later versions

### ISSUE THREAD

**Issue by elacheche** [gvmtool/gvm-cli#352]
As explained in the title, the Ubuntu PPA needs to be maintained.. https://launchpad.net/~groovy-dev

**Comment by marcoVermeulen** [comment]
This has nothing to do with GVM at all. The old PPA was merely for installing groovy, grails and griffon on ubuntu.

GVM has superseded the need of having specific ubuntu (or brew, or name your own package manager) packages. GVM installs the sdks in a platform agnostic way.
